name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: wasm32-wasi

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-

    - name: Cache target directory
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-target-wasm-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-target-wasm-

    - name: Check code formatting
      run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy --target wasm32-wasi -- -D warnings

    - name: Build extension
      run: cargo build --release --target wasm32-wasi

    - name: Prepare artifact
      run: |
        mkdir -p dist
        cp target/wasm32-wasi/release/emmylua.wasm dist/
        cp extension.toml dist/
        cp README.md dist/
        cp -r languages dist/
        ls -lah dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: emmylua-extension
        path: dist/*
        retention-days: 30

  validate:
    name: Validate Extension
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: emmylua-extension
        path: dist/

    - name: Validate extension structure
      run: |
        echo "Checking required files..."
        ls -la dist/
        test -f dist/extension.toml || (echo "❌ extension.toml not found" && exit 1)
        test -f dist/emmylua.wasm || (echo "❌ emmylua.wasm not found" && exit 1)
        test -d dist/languages || (echo "❌ languages directory not found" && exit 1)
        test -f dist/languages/emmylua/config.toml || (echo "❌ languages/emmylua/config.toml not found" && exit 1)
        echo "✅ All required files found!"

    - name: Check WASM file size
      run: |
        WASM_SIZE=$(stat -f%z dist/emmylua.wasm 2>/dev/null || stat -c%s dist/emmylua.wasm)
        echo "WASM file size: $(numfmt --to=iec-i --suffix=B $WASM_SIZE)"
        if [ $WASM_SIZE -gt 10485760 ]; then
          echo "⚠️  Warning: WASM file is larger than 10MB"
        else
          echo "✅ WASM file size is acceptable"
        fi

